services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1

#  eureka-server:
#    build: eureka-server
#    container_name: eureka-server
#    ports:
#      - "5767:5767"
#    environment:
#      SERVER_PORT: "5767"
#
#  postgres:
#    image: postgres:16.0-alpine
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: social
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  api-gateway:
#    build: api-gateway
#    container_name: api-gateway
#    ports:
#      - "8081:8081"
#    environment:
#      SERVER_PORT: 8081
#    depends_on:
#      - eureka-server
#
#  user-module:
#    build: user-module
#    container_name: user-module
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    depends_on:
#      - postgres
#      - eureka-server
#
#  post-module:
#    build: post-module
#    container_name: post-module
#    ports:
#      - "8282:8282"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    depends_on:
#      - postgres
#      - eureka-server
#
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    ports:
#      - "5050:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: postgres@mail.ru
#      PGADMIN_DEFAULT_PASSWORD: password
#    depends_on:
#      - postgres

volumes:
  postgres_data: