spring:
    application:
        name: user-module

    datasource:
        url: jdbc:postgresql://localhost:5432/social
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

#    data:
#        redis:
#            host: redis
#            port: 6379
#            timeout: 2000
#            lettuce:
#                pool:
#                    max-active: 8
#                    max-idle: 8
#                    min-idle: 0

server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 30

security:
    jwt:
        access-secret: VOe5bgn1j6uY+bz0VpoRx/Ns+iDvzGnGM58BqBaanFizwEdCMzlMjPisolnSxQUh0PCgxKqqKtWAeUJzr2bN2A==
        refresh-secret: KRLeMz77TA1D+uEo4iJbYJcaGgUy6IDzrPw440tAkJU+7cfLjtau8JHnoIAIRvUwRrOMtWq96HX2NYa0YUYKGQ==
