server:
    port: 8080

spring:
    application:
        name: user-module
    main:
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:postgresql://localhost:5432/social
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        deserialization:
            fail-on-unknown-properties: true

security:
    jwt:
        refresh-secret: "KRLeMz77TA1D+uEo4iJbYJcaGgUy6IDzrPw440tAkJU+7cfLjtau8JHnoIAIRvUwRrOMtWq96HX2NYa0YUYKGQ=="
#eureka:
#    instance:
#        preferIpAddress: true
#    client:
#        registerWithEureka: true
#        fetchRegistry: true
#        serviceUrl:
#            defaultZone: http://localhost:5767/eureka

logging:
    level:
        org.springframework.cloud.gateway: DEBUG             # Логирование для Spring Cloud Gateway
        reactor.netty.http.client: DEBUG                      # Логирование для реактивного HTTP клиента
        org.springframework.web: DEBUG                        # Логирование для Spring Web
        org.hibernate.SQL: DEBUG                               # Логирование SQL-запросов Hibernate
        org.springframework.orm.jpa: DEBUG                    # Логирование запросов JPA
